apiVersion: v1
kind: ConfigMap
metadata:
  name: forum-configmap
  namespace: app
data:
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: http://10.0.2.2/realms/code-help
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: http://iam-service.app.svc.cluster.local/realms/code-help/protocol/openid-connect/certs
  SPRING_DATASOURCE_USERNAME: user
  SPRING_DATASOURCE_URL: jdbc:postgresql://forum-db-service.db.svc.cluster.local:5432/code_help
  SERVER_PORT: '3001'
