apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: core-db
  namespace: db
spec:
  serviceName: core-db-service
  selector:
    matchLabels:
      app: core-db
  template:
    metadata:
      labels:
        app: core-db
    spec:
      containers:
        - name: core-db
          resources:
            limits:
              memory: '1Gi'
              cpu: '500m'
          image: neo4j:5.2.0
          volumeMounts:
            - mountPath: /data
              name: core-db-data
          envFrom:
            - secretRef:
                name: core-db-secret
                optional: false
          ports:
            - name: http
              containerPort: 7474
            - name: bolt
              containerPort: 7687
  volumeClaimTemplates:
    - metadata:
        name: core-db-data
        namespace: db
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 1Gi