apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-db
  namespace: db
spec:
  selector:
    matchLabels:
      app: forum-db
  template:
    metadata:
      labels:
        app: forum-db
    spec:
      containers:
        - name: forum-db
          image: postgres:15.1-alpine
          resources:
            limits:
              memory: '1Gi'
              cpu: '500m'
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: forum-db-configmap
            - secretRef:
                name: forum-db-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: forum-db-postgres-data
      volumes:
        - name: forum-db-postgres-data
          persistentVolumeClaim:
            claimName: forum-db-pvc
