apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forum-db-pvc
  namespace: db
spec:
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
